Medable/mdctl

packages/mdctl-cli/mdctl.js
packages/mdctl-credentials-provider-pouchdb/index.js

Gracefully handles the case where `~/.medable` directory does not exist; automatically creates directory.  This stops credentials commands from throwing errors such as...
```
› mdctl credentials add
? Which type of credentials are you using? Password - Email/Username and Password
? The api endpoint (example: https://api.dev.medable.com) blah.medable.com
? The env (org code) myorgcode
? The account username myemail
? The account password [hidden]
? The api key somekeysahkbfdhas
events.js:173
throw er; // Unhandled 'error' event
^
error: SQLITE_CANTOPEN: unable to open database file
Emitted 'error' event at:
```

Create config folder if missing

---

packages/mdctl-api/adapters/index.js

When cancelling a stream using `stream.destroy` I encountered the following error:
```
_stream_writable.js?2135:288 Uncaught (in promise) error: write after end
at writeAfterEnd (webpack-internal:///../../node_modules/readable-stream/lib/_stream_writable.js:288:12)
at TransformStream.Writable.write (webpack-internal:///../../node_modules/readable-stream/lib/_stream_writable.js:332:20)
at eval (webpack-internal:///../../node_modules/@medable/mdctl-api/adapters/index.js:119:17)
```
This pr adds check for `transform.writable` before writing, which seems to fix the issue

add check for `transform.writable` before writing

---

packages/mdctl-api/client.js

Allow for cancelToken, upload and download progress to be set per request, not only on client instantiation.

remove cancelToken and others from default requestOptions

---

package-lock.json
packages/mdctl-axon-tools/.eslintrc
packages/mdctl-axon-tools/.gitignore
packages/mdctl-axon-tools/.npmignore
packages/mdctl-axon-tools/README.md
packages/mdctl-axon-tools/index.js
packages/mdctl-axon-tools/lib/StudyManifestTools.js
packages/mdctl-axon-tools/package-lock.json
packages/mdctl-axon-tools/package.json
packages/mdctl-axon-tools/packageScripts/consentIngestTransform.js
packages/mdctl-axon-tools/packageScripts/package.json
packages/mdctl-axon-tools/packageScripts/taskIngestTransform.js
packages/mdctl-axon-tools/packageScripts/taskInjestTransform.js
packages/mdctl-axon-tools/test.js
packages/mdctl-cli/lib/studyQuestions.js
packages/mdctl-cli/package-lock.json
packages/mdctl-cli/package.json
packages/mdctl-cli/tasks/study.js

This new feature adds a new axon tools package that initially contains manifest generation tools. The CLI has been extended to allow the export of studies/tasks/consent directly using MDCTL. Along with the features provided to the existing standalone tools we are adding/extending the following features:
- Study exports:
- No longer limited object requests
- Inclusion of consent templates in standard study exports
- More robust referential integrity validation
- Inclusion of package file with export
- broken reference report 
- owner property not exported
- Task exports
- Multi-task selection  
- Ingest transform utilized to allow the import to any org without extra tools
- Consent exports
- Multi-consent selection  
- Ingest transform utilized to allow the import to any org without extra …

Addition of library and CLI commands to support study data import/export

---

packages/mdctl-axon-tools/lib/StudyManifestTools.js

'ec__default_document_css' needed to be pluralized when being plugged into getExportObjects()
added default css object to ec export

TOOLS-25 - fixed export of default css

---

packages/mdctl-axon-tools/packageScripts/ingestTransform.js

updated ingestTransform to throw an error specifically when the study being imported does not match the study that exists in the target environment
Previously, the error that was thrown was a duplicateKey error because the field c_unique_key must be unique and can only contain the string 'c_unique_key', therefore, if any other study were to be created and have that required field populated, it would throw a duplicateKey error. To help end users know exactly what is wrong, we now use the ingest transform to compare the c_keys of the imported and existing studies, then throw an error saying that another study already exists if that is the case.

MIG-58 - explicit error for importing diff study

---

packages/mdctl-axon-tools/__tests__/MIG-67/MIG-67.test.js
packages/mdctl-axon-tools/__tests__/TOOLS-42/TOOLS-42.test.js
packages/mdctl-axon-tools/lib/StudyManifestTools.js

Improve issues report logs, to make it clear that objects that depend on a missing object will not be exported.

Improve issues-report messages

---

packages/mdctl-axon-tools/__tests__/MIG-109/MIG-109.test.js
packages/mdctl-axon-tools/lib/StudyManifestTools.js

Requirements
- [MIG-109](https://jira.devops.medable.com/browse/MIG-109)
Notes
- This is necessary for [AXD-46](https://jira.devops.medable.com/browse/AXD-46). The current logic of getStudyManifest function in StudyManifestTools module will be split into 2 new functions called buildManifestAndDependencies and writeToDisk; the former function will generate all relevant data objects and the latter will write files on the disk.

MIG-109: split getStudyManifest function as per requirement

---

packages/mdctl-axon-tools/__tests__/MIG-63/MIG-63.test.js
packages/mdctl-axon-tools/lib/mappings/index.js
packages/mdctl-axon-tools/lib/mappings/maps/EcBuilderDataMap.js
packages/mdctl-axon-tools/lib/mappings/maps/index.js

ec__document_template.ec__builder_data contains strings that include _id's in them, which did not get updated during migration, even though the _id's change as a result of migration. This mapping updates those strings to reference the new _id's

MIG-126 - ec__builder_data id mappings

---

packages/mdctl-axon-tools/lib/StudyManifestTools.js
packages/mdctl-cli/lib/studyQuestions.js

Because in most cases the template titles (names) are pretty similar, we have added the template ID so it's easier for the user to pick the template they want to export.

Added template ID in the select consent templates list when exporting

---

packages/mdctl-axon-tools/__tests__/MIG-136/MIG-136.test.js
packages/mdctl-axon-tools/lib/StudyManifestTools.js

Implemented requirements as per [MIG-136](https://jira.devops.medable.com/browse/MIG-136). 
These changes limit the object records displayed in MDCTL to the only study that should exist in an org, so that users are presented with invalid records (i.e. orphan records related to deleted studies) 

restricted task and templates to available study and added unit tests

---

packages/mdctl-core/streams/section.js
packages/mdctl-core/test/section_template_test.js
packages/mdctl-node-utils/crypto.js

Required by i18n Initiative. 
Multiple locales supported via array per template file. New fn is backward compatible as well for the old style of export. 
If one locale, then template file is named according to that. If multiple, then its a hash of the locales array. Otherwise, if it is * then the template file is named anyLocale. 
Things to consider: 
1. Ordering of the locales array before we hashing, as the hash will change otherwise. 
2. Publishing the node-utils package as we're using a new function added to the crypto library

Added support for multiple locales per template file

---

packages/mdctl-axon-tools/__tests__/MIG-85/MIG-85.test.js
packages/mdctl-axon-tools/lib/StudyManifestTools.js
packages/mdctl-cli/tasks/study.js
packages/mdctl-cli/test/tasks/study.js

Extended list of exportable objects on partial migrations as per  [MIG-143](https://jira.devops.medable.com/browse/MIG-143). MDCTL now will allow partial migration of the following object instances:
- Study Details
- Anchor Dates
- Participant Schedules
- Participant Flags
- Tasks (already exists)
- Task Assignments
- Sites
- Visit Schedules
- Groups
- Templates (already exists)
- Reports
- Faults
- Looker

MIG-143: extended partial object list and updated tests

---

packages/mdctl-api-driver/lib/cursor.js
packages/mdctl-api-driver/package.json
packages/mdctl-axon-tools/package.json

`stream-to-iter` functionality has been included since version 10 of node. Removing this dependency will remove bad engine warning during installation:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'stream-to-iterator@3.0.3',
npm WARN EBADENGINE   required: { node: '>=8.9 <10' },
npm WARN EBADENGINE   current: { node: 'v16.18.1', npm: '8.19.2' }
npm WARN EBADENGINE }
```

Remove deprecated stream-to-iter

---

packages/mdctl-axon-tools/__tests__/MIG-154/MIG-154.test.js
packages/mdctl-axon-tools/__tests__/MIG-156/MIG-156.test.js
packages/mdctl-axon-tools/lib/StudyManifestTools.js
packages/mdctl-cli/tasks/study.js
packages/mdctl-cli/test/tasks/study.js

Created a new flag, called excludeTemplates: when set to "true", eTemplates will not be exported as part of a study export. Default value is false.
Requirement: [MIG-156](https://jira.devops.medable.com/browse/MIG-156)
TDD: [MIG-1.4.0](https://docs.google.com/document/d/1w6ITrDqx8IuJ7beHi6nG4Ih2lu5NF6AiSkZre_bl9LI/edit#)

MIG-156 : added flag to exclude eTemplates from study export

---

packages/mdctl-axon-tools/lib/StudyManifestTools.js
packages/mdctl-cli/lib/studyQuestions.js
packages/mdctl-cli/tasks/study.js

Adds `mdctl study data-transfer` to export all data transfer related object (dt__config, dt__export, dt__execution). To import to new organization the already existing `mdctl study import` could be used.

PDT-769 Add mdctl study data-transfer to export dt details

---

packages/mdctl-axon-tools/__tests__/MIG-148/MIG-148.test.js
packages/mdctl-axon-tools/__tests__/MIG-154/MIG-154.test.js
packages/mdctl-axon-tools/__tests__/MIG-63/MIG-63.test.js
packages/mdctl-axon-tools/__tests__/TOOLS-42/TOOLS-42.test.js
packages/mdctl-axon-tools/lib/StudyManifestTools.js
packages/mdctl-axon-tools/lib/mappings/index.js
packages/mdctl-axon-tools/lib/mappings/maps/EcBuilderDataMap.js
packages/mdctl-axon-tools/lib/mappings/maps/index.js

Fixed ECBuilderMap and script to update only ids in ec_builder_data and export only draft templates in the target org
**Changes in export:**
- Fixed the Ec builder data map to contain only ids and `ec_keys`
- Export Builder data maps for affected templates only(those being exported)
- Export Builder data maps for published templates as well, if they are being exported
**Changes in import:** 
- Update only the ids of the `ec__builder_data` in target org
- Update template in the target org only if they are in draft status
**Common:**
- Fixed tests

MIG-171 - Fixed ECBuilderMap and script

---

.github/workflows/alpha.yml
.github/workflows/latest.yml
default.nix

this PR should include changes that will make it easier to release alphas and golden releases of mdctl to npm!

attempt to fixup release workflows, update nix env

---

packages/mdctl-axon-tools/__tests__/MIG-156/MIG-156.test.js
packages/mdctl-axon-tools/__tests__/MIG-180/MIG-180.test.js
packages/mdctl-axon-tools/__tests__/MIG-85/MIG-85.test.js
packages/mdctl-axon-tools/lib/StudyManifestTools.js
packages/mdctl-axon-tools/packageScripts/ingestTransform.js
packages/mdctl-cli/lib/studyQuestions.js
packages/mdctl-cli/tasks/study.js
packages/mdctl-import-adapter/__tests__/MIG-121/template-export/ingestTransform.js

This PR provides the options to export/import the  workflow objects.
Changes:
- New study command to selective export of workflow object
- Import feature of workflow object
- Study export includes workflow object only if `workflow__version` config is present
Commands: 
```
mdctl study workflows export
mdctl study import
```

DCT-353 mdctl update to support workflows export/import

---

packages/mdctl-axon-tools/__tests__/MIG-85/MIG-85.test.js
packages/mdctl-axon-tools/lib/StudyManifestTools.js

In this PR we are adding the recently introduced object `c_review_type` to the study exports and imports so all of its instances can be exported and imported by default with the `mdctl study export` and `mdctl study import` commands.

Include object `c_review_type` in study exports & imports

---

packages/mdctl-axon-tools/lib/StudyManifestTools.js

Verifies that the tasks, steps and notifications that are associated
with a workflow is present in the environment when a workflow is
exported. Does not proceed with the export process if any of them are
not present

StudyManifestTools: Check reference before export

---

packages/mdctl-cli/lib/env/export.js
packages/mdctl-core/streams/export_stream.js

This MR introduces a mechanism to detect stream termination, aiming to provide a clearer distinction between streams that end normally and those terminated due to the process being killed unexpectedly. 
The last thing cortex-api emits in an export is the `manifest-exports` object, which will always be present in an export. Receiving this object signals the end of the stream.

detect end of export stream

---

packages/mdctl-cli/tasks/study.js

**Current `mdctl study` documentation**
```
~/github/Medable/mdctl  update_study_tasks_documentation ................................ direnv  system node  impure nix  11:25:23
> mdctl help study
Study Tools
Usage:
mdctl study [command]
Arguments:
Command
export - Exports the study from the current org
import - Imports the study into the current org
task [action] - Allows the select of tasks to export from the current org
consent [action] - Allows the select of consent templates to export from the current org
workflow [action] - Allows the select of workflow templates to export from the current org
data-transfer - Allows the select of data transfer configs to export from the current org
```
**Current behavior for `task` command**
```
> mdctl study task --env env.orgCode
{
object: 'fault', …
```

Updates mdctl study documentation to list the correct tasks command

---

.github/workflows/mdctl-core-tests.yml
package-lock.json
packages/mdctl-cli/lib/env/export.js
packages/mdctl-core/.gitignore
packages/mdctl-core/.mocharc.json
packages/mdctl-core/package.json
packages/mdctl-core/streams/export_stream.js
packages/mdctl-core/streams/section.js
packages/mdctl-core/test/export_stream.test.js
packages/mdctl-core/test/section.test.js

The PR focuses on optimizing the `extractAssets` process, with changes including:
- using `sectionsWithResources` instead of  `SectionsCreated` to save only sections that contain resources. We also search the content document for resources in the constructor in order to do it only once per section.
- `sectionsWithResources` will be passed from the export_stream.

CTXAPI-2569: Improve extractAssets to minimize memory and CPU consumption
