packages/mdctl-core/streams/section.js

adding changes to add type to template name

---

packages/mdctl-cli/lib/env/import.js

cli options not picked up for env import

Closes CTXTOOLS-43

---

packages/mdctl-cli/mdctl.js

adding changes to support env vars and adding password/token to list for file

---

packages/mdctl-import-adapter/index.js
packages/mdctl-import-adapter/package.json

Please check this out @jsas, Thanks

CTXTOOLS-47: Load instance data from manifest.

---

packages/mdctl-api-driver/README.md
packages/mdctl-api/request.js

adding fix for mdctl-api request, add documentation

---

packages/mdctl-api/request.js
packages/mdctl-cli/tasks/env.js

Please check this out @jsas , thanks

CTXTOOLS-57: adding changes to parse stream error response

---

packages/mdctl-api-driver/package-lock.json
packages/mdctl-api/adapters/index.js
packages/mdctl-api/adapters/xhr.js
packages/mdctl-api/client.js
packages/mdctl-api/package-lock.json
packages/mdctl-api/package.json
packages/mdctl-api/request.js
packages/mdctl-cli/package-lock.json
packages/mdctl-core-schemas/package-lock.json
packages/mdctl-core-utils/package-lock.json
packages/mdctl-core/package-lock.json
packages/mdctl-credentials-provider-keychain/package-lock.json
packages/mdctl-credentials-provider-pouchdb/package-lock.json
packages/mdctl-export-adapter-console/package-lock.json
packages/mdctl-export-adapter-tree/package-lock.json
packages/mdctl-import-adapter/package-lock.json
packages/mdctl-manifest/package-lock.json
packages/mdctl-node-utils/package-lock.json
packages/mdctl-sandbox/package-lock.json
packages/mdctl-secrets/package-lock.json

Feature/CTXTOOLS-58: streaming support for browsers

---

packages/mdctl-api-driver/lib/cursor.js
packages/mdctl-api/adapters/index.js
packages/mdctl-api/adapters/xhr.js

stop reading when writable stream gets destroyed or ended, change inherited transform stream in cursor driver

---

packages/mdctl-cli/tasks/env.js
packages/mdctl-cli/tasks/sandbox.js
packages/mdctl-cli/tasks/tail.js
packages/mdctl-core-utils/values.js
packages/mdctl-sandbox/sandbox.js

tail command supported in cortex 2.13.0

Added tail command and --ndjson option to sandbox

---

packages/mdctl-api/client.js
packages/mdctl-api/request.js
packages/mdctl-cli/tasks/tail.js

client and request should make response available even when streaming a response.

WIP: tail reconnects after timeout

---

packages/mdctl-cli/tasks/env.js
packages/mdctl-core/streams/export_stream.js
packages/mdctl-core/streams/section.js

CTXTOOLS-71: adding resource.json export, also adding missing dir options in env export/import

---

packages/mdctl-api/client.js
packages/mdctl-core-utils/values.js

support passing absolute url into api client

---

packages/mdctl-cli/README.md
packages/mdctl-cli/lib/env/export.js
packages/mdctl-import-adapter/index.js

Adds more package.json script import/export support (before/after export, ingest streaming)

Close CTXTOOLS-96

---

packages/mdctl-api-driver/lib/driver.js
packages/mdctl-core/credentials/environment.js

add node path

---

packages/mdctl-axon-tools/lib/StudyManifestTools.js

Fix bug caused by adding c_dmweb_reports

Fix for object with no reference property

---

packages/mdctl-axon-tools/__tests__/TOOLS-42/TOOLS-42.test.js
packages/mdctl-axon-tools/__tests__/TOOLS-44/TOOLS-44.test.js
packages/mdctl-axon-tools/packageScripts/ingestTransform.js

Depends on PR: https://github.com/Medable/mdctl/pull/288

TOOLS-44: import a late bound unknown resource failed to resolve to an existing object

---

packages/mdctl-axon-tools/__tests__/TOOLS-42/TOOLS-42.test.js
packages/mdctl-axon-tools/lib/StudyManifestTools.js

I was missing the case when the reference is a simple ObjectId and not an ObjectId[]

MIG-65: Export type error error code 'object id arr.map is not a function'

---

packages/mdctl-axon-tools/__tests__/MIG-63/MIG-63.test.js
packages/mdctl-axon-tools/__tests__/TOOLS-42/TOOLS-42.test.js
packages/mdctl-axon-tools/lib/StudyManifestTools.js
packages/mdctl-axon-tools/lib/mappings/MenuConfigMapping.js

This is not a comprehensive solution to add mappings but for now solves this particular issue, the code was written with some considerations to later extend this.

MIG-63: Export/import menu config is not being migrated for studies created prior to axc 4.17.0

---

packages/mdctl-api-driver/lib/cortex.object.js
packages/mdctl-api-driver/test/driver.js

https://jira.devops.medable.com/browse/MIG-124

Changed method to correctly record objects and aliases, and added test

---

package-lock.json
packages/mdctl-axon-tools/__tests__/MIG-109/MIG-109.test.js
packages/mdctl-axon-tools/__tests__/MIG-148/MIG-148.test.js
packages/mdctl-axon-tools/__tests__/MIG-154/MIG-154.test.js
packages/mdctl-axon-tools/__tests__/MIG-63/MIG-63.test.js
packages/mdctl-axon-tools/__tests__/MIG-85/MIG-85.test.js
packages/mdctl-axon-tools/__tests__/TOOLS-50/TOOLS-50.test.js
packages/mdctl-axon-tools/lib/StudyManifestTools.js
packages/mdctl-axon-tools/lib/mappings/maps/EcBuilderDataMap.js

Summary of changes:
- improved compatibility with older studies where certain objects are always assumed to be “exportable”; this is generally true for more recent studies, i.e. studies built using Axon > v4.14.5 but for older study it might not always be the case.
- fixed a minor bug in the code that doesn’t check the presence of a nested object in eTemplates: this was noticed to occur with eConsent-environment v1.2.3
For more details refer to [TDD](https://docs.google.com/document/d/1w6ITrDqx8IuJ7beHi6nG4Ih2lu5NF6AiSkZre_bl9LI/edit#heading=h.y3o6oq7jijg3)

MIG-154 increased compatibility with older studies

---

packages/mdctl-core/streams/export_stream.js
packages/mdctl-core/streams/section.js
packages/mdctl-manifest/manifest.js

Adds support for importing and exporting named expressions

add expressions support for import/export

---

.github/workflows/axon-tools-tests.yml
package-lock.json
packages/mdctl-axon-tools/.gitignore
packages/mdctl-axon-tools/jest.config.js
packages/mdctl-axon-tools/package.json

Add an html report and upload it as an artifact

add html report
